apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: hypercloud5-system
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hypercloud5-system
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: tmaxcloudck/postgres-cron:{HPCD_POSTGRES_VERSION}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: TZ
            value: 'Asia/Seoul'
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "300m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - mountPath: /docker-entrypoint-initdb.d
              name: initdbsql
      serviceAccountName: hypercloud5-admin    
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data
      - name: initdbsql
        configMap:
          name: postgres-init-config
          items:
          - key: INIT_DB_SQL
            path: init-db.sql
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: hypercloud5-system
spec:
  #storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hypercloud5-system
type: Opaque
data:
  POSTGRES_PASSWORD: dG1heA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
  namespace: hypercloud5-system
data:
  INIT_DB_SQL: |-
    CREATE TABLE AUDIT (ID VARCHAR(64) NOT NULL, USERNAME VARCHAR(255), USERAGENT VARCHAR(255), NAMESPACE VARCHAR(255), APIGROUP VARCHAR(255), APIVERSION VARCHAR(32), RESOURCE VARCHAR(64), NAME VARCHAR(255), STAGE VARCHAR(32), STAGETIMESTAMP TIMESTAMP NOT NULL, VERB VARCHAR(32), CODE INT, STATUS VARCHAR(255), REASON VARCHAR(255), MESSAGE VARCHAR(255));
    CREATE INDEX TIME_INDEX ON AUDIT (STAGETIMESTAMP);
    ALTER DATABASE postgres set idle_in_transaction_session_timeout = '3min';