apiVersion: v1
kind: Service
metadata:
  name: audit-webhook-server-service
  namespace: hypercloud5-system
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    hypercloud5: audit-webhook-server
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-webhook-server
  namespace: hypercloud5-system
  labels:
    hypercloud5: audit-webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud5: audit-webhook-server
  template:
    metadata:
      name: audit-webhook-server
      namespace: hypercloud5-system
      labels:
        hypercloud5: audit-webhook-server
    spec:
      serviceAccount: default
      containers:
        - name: audit-webhook-server
          image: tmaxcloudck/audit-webhook-server:{AUDIT_WEBHOOK_SERVER_VERSION}
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: GODEBUG
              value: "x509ignoreCN=0"  
            - name: timescaledb_password
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: POSTGRES_PASSWORD
          ports:
          - containerPort: 80
            name: http
          resources:
            limits:
              cpu: "300m"
              memory: "300Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
